"""Central scoring weights for v1.3 DNS integration.

Weights are impact-oriented. Unknown/unverifiable findings may carry their
nominal weight but must set ``applicable=False`` so they never reduce score.
"""

NAME_SERVER_REDUNDANCY_WEIGHT = 3
DELEGATION_CONSISTENCY_WEIGHT = 6
DELEGATED_AUTHORITY_WEIGHT = 7
NAMESERVER_ADDRESSABILITY_WEIGHT = 7
DNSSEC_SCORE_WEIGHT = 10
DNSSEC_UNSIGNED_EARNED = 5
OPEN_RECURSION_WEIGHT = 8
AUTHORITATIVE_TCP_WEIGHT = 2
AUTHORITATIVE_RRSET_WEIGHT = 3
CAA_MALFORMED_WEIGHT = 2

__all__ = [
    "NAME_SERVER_REDUNDANCY_WEIGHT",
    "DELEGATION_CONSISTENCY_WEIGHT",
    "DELEGATED_AUTHORITY_WEIGHT",
    "NAMESERVER_ADDRESSABILITY_WEIGHT",
    "DNSSEC_SCORE_WEIGHT",
    "DNSSEC_UNSIGNED_EARNED",
    "OPEN_RECURSION_WEIGHT",
    "AUTHORITATIVE_TCP_WEIGHT",
    "AUTHORITATIVE_RRSET_WEIGHT",
    "CAA_MALFORMED_WEIGHT",
]
